### ISSUE TITLE
fs.writeFile throws ERR_INVALID_CALLBACK error

### ISSUE THREAD

**Issue by joarder** [awslabs/aws-data-lake-solution#37]
**Versions:**
NodeJS version: v12.12.0
OS: Mac OS X 10.14.6

The following error occurs while building the solutions with the command
`./build-s3-dist.sh $DEPLOY_BUCKET $VERSION_CODE`

**Detail error message:**
```
fs.js:135
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at Object.<anonymous> (/Users/-/Documents/workspace/aws-data-lake-solution/deployment/manifest-generator/app.js:70:4)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_INVALID_CALLBACK'
}
```

**Fix:**

In file [aws-data-lake-solution/deployment/manifest-generator/app.js](https://github.com/awslabs/aws-data-lake-solution/blob/fa800dd1b2339184377742a6dc96b1e53f47b6ff/deployment/manifest-generator/app.js#L70) Line 70 should be:
`fs.writeFileSync('../dist/data-lake-site-manifest.json', JSON.stringify(_manifest, null, 4));`
instead of:
`fs.writeFile('../dist/data-lake-site-manifest.json', JSON.stringify(_manifest, null, 4));`

**Comment by beomseoklee** [comment]
Thanks for your input, and I am sorry about your inconvenience. We will consider to fix this one in the next release.

**Comment by georgebearden** [comment]
This issue should be addressed in the latest commit. Please let us know if you need additional assistance.
